version: "3.8"

services:
  interlock-postgres:
    container_name: interlock-postgres
    image: postgres:14.13
    env_file:
      - ./.env
    volumes:
      - ./dump:/data/dump
      - postgres:/data/postgres:rw
      - postgresconfig:/var/lib/postgresql/data:rw
    ports:
      - 5439:5432
    hostname: interlock-postgres
    networks:
      - interlock-network
    restart: unless-stopped

  eureka:
    image: node:20-alpine
    working_dir: /app/eureka
    volumes:
      - ./eureka:/app/eureka
    env_file:
      - ./eureka/.env
    depends_on:
      - interlock-postgres
    networks:
      - interlock-network
    command: >
      sh -c "npm install &&
              npx prisma generate &&
              npx prisma migrate reset --force"

  passmark:
    image: node:20-alpine
    working_dir: /app/passmark
    volumes:
      - ./passmark:/app/passmark
    env_file:
      - ./passmark/.env
    depends_on:
      - interlock-postgres
    networks:
      - interlock-network
    command: >
      sh -c "npm install &&
              npx prisma generate &&
              npx prisma migrate reset --force"

  interlock-pgadmin:
    container_name: interlock-pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./.env
    depends_on:
      - interlock-postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5040:80
    networks:
      - interlock-network
    hostname: interlock-pgadmin
    restart: unless-stopped

networks:
  interlock-network:
    driver: bridge
    external: true

volumes:
  postgres:
  pgadmin:
  postgresconfig:
